name: Rg Gabunada
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32598
title: Rg Gabunada
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f0f3'
    - '#b2a89f'
    - '#003717'
    - '#a18874'
    - '#91684a'
  brandStrength: 0.5
  lightness: 0.02544915722683072
  saturation: 0.875
  rhythmicContrast: 0.6498896162956953
purpose: []
